alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
  features:
  - buildpack-stack=ubuntu-22
  ingress:
    rules:
    - component:
        name: skills-003-teaching-system
      match:
        authority:
          exact: ""
        path:
          prefix: /
  name: squid-app
  region: blr
  services:
  - http_port: 5000
    image:
      registry: skills003
      registry_type: DOCKER_HUB
      repository: teaching-system
      tag: v1.1
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    name: skills-003-teaching-system
